### ISSUE TITLE
Nothing happens on macOS

### ISSUE THREAD

**Issue by Almis90** [DrafaKiller/CodeScanner-flutter#2]
I tested it on the web and it works, on macOS nothing happens. At first it was crashing, I needed to install camera_avfoundation to fix the crash.

**Comment by DrafaKiller** [comment]
The package is labeled as **Android and iOS only**.

It's good to know that it's possible to use it as it is for web, and for macOS with a simple install.
The **camera** dependency being used is not implemented for macOS.

Right now I'm busy with other projects, but I will add an implementation for web and macOS platforms in the future, when I have time. Unless someone else makes a pull request addressing that.

**Comment by DrafaKiller** [comment]
As I said in the mentioned issue, this will not be possible.

> The Google's ML Kit dependency is only implemented for mobile, and looks like there aren't any easy and quick AI Vision packages for scanning QR Codes and Barcodes outside the mobile environment.

The platform compatibility labeled on pub.dev was fixed, without having to do anything, sorry for the inconvenience.
For now it's not planned make it compatible with all platforms, **unless there's an AI Vision available for all platforms**.
