### ISSUE TITLE
Dependency `GTMSessionFetcher/Core` version incompatibility

### ISSUE THREAD

**Issue by MrMagloire** [DrafaKiller/CodeScanner-flutter#4]
Hello, Thank you for all.
I am facing a bug such as : 
`[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In snapshot (Podfile.lock):
    GTMSessionFetcher/Core (< 3.0, = 2.1.0, >= 1.7)

  In Podfile:
    google_mlkit_barcode_scanning (from `.symlinks/plugins/google_mlkit_barcode_scanning/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/BarcodeScanning (\~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitBarcodeScanning (\~> 2.1.0) was resolved to 2.1.0, which depends on
          MLKitCommon (\~> 7.0) was resolved to 7.0.0, which depends on
            GTMSessionFetcher/Core (\~> 1.1)

You have either:
 * changed the constraints of dependency `GTMSessionFetcher/Core` inside your development pod `google_mlkit_barcode_scanning`.
   You should run `pod update GTMSessionFetcher/Core` to apply changes you've made.`

**Comment by DrafaKiller** [comment]
Have you tried to run `pod update GTMSessionFetcher/Core`?

---

There are compatibility issues with the packages you're using. If the previous command doesn't work, then you're using incompatible packages. This is a compatibility issue with one of the dependencies of this package, not this package itself.

Sadly there's nothing I can do in this package to help with your issue, you might need to open this issue in the [google_mlkit_barcode_scanning](https://github.com/bharat-biradar/Google-Ml-Kit-plugin) dependency.

**Comment by MrMagloire** [comment]
Thank you all is okay
